version: "3"
services:
  server:
    container_name: "server"
    build: ./
    ports:
      - "3000:3000"
    environment:
      PG_HOST: database
    depends_on:
      - database
  database:
    image: "postgres:12"
    container_name: "postgres"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${PG_DATABASE}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    volumes:
      - database-data:/var/lib/postgresql/data/
    env_file:
      - .env
volumes:
  database-data:
